Repository CZERTAINLY/CZERTAINLY-EJBCA-NG-Connector, pull requests merged in 2023-07, with the labels that each got.

#47 Fix discovery data request pagination
  pom.xml
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryServiceImpl.java
Labels: bug

#48 Update discovery of certificates on EJBCA version 7.11 and higher
  README.md
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryAttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/util/EjbcaVersion.java
  src/main/resources/application.yml
Labels: enhancement

#49 Release/1.5.0
  README.md
  pom.xml
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoveryControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryAttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/util/EjbcaVersion.java
  src/main/resources/application.yml
Labels: ignore-for-release

#50 Update release version
  pom.xml
Labels: ignore-for-release
