Repository CZERTAINLY/CZERTAINLY-EJBCA-NG-Connector, pull requests merged in 2023-02, with the labels that each got.

#38 Upgrade java to version 17
  .github/workflows/build.yml
  Dockerfile
  pom.xml
Labels: enhancement

#37 Load and merge trusted certificates during start
  README.md
  docker/opt/czertainly/entry.sh
  src/main/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfig.java
  src/test/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfigTest.java
Labels: enhancement

#39 Fix loading of default truststore in ssl context
  src/main/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfig.java
  src/main/java/com/czertainly/ca/connector/ejbca/rest/EjbcaRestApiClient.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AuthorityInstanceServiceImpl.java
Labels: bug

#40 Support read-only file systems
  Dockerfile
  src/main/java/com/czertainly/ca/connector/ejbca/config/EmbeddedServletContainerConfig.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#41 Fix sonarqube reported issues
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoveryAttributesControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfig.java
Labels: bug, ignore-for-release

#42 Release 1.3.0
  .github/workflows/build.yml
  Dockerfile
  README.md
  docker/opt/czertainly/entry.sh
  pom.xml
  src/main/java/com/czertainly/ca/connector/ejbca/Application.java
  src/main/java/com/czertainly/ca/connector/ejbca/EndpointsListener.java
  src/main/java/com/czertainly/ca/connector/ejbca/ExceptionHandlingAdvice.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/AttributesControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/AuthorityInstanceControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/CertificateControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoveryAttributesControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/DiscoverySupportController.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/EndEntityProfilesControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/api/InfoControllerImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/config/CustomAsyncConfigurer.java
  src/main/java/com/czertainly/ca/connector/ejbca/config/EmbeddedServletContainerConfig.java
  src/main/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfig.java
  src/main/java/com/czertainly/ca/connector/ejbca/dao/entity/AuthorityInstance.java
  src/main/java/com/czertainly/ca/connector/ejbca/dao/entity/Certificate.java
  src/main/java/com/czertainly/ca/connector/ejbca/enums/JavaMigrationChecksums.java
  src/main/java/com/czertainly/ca/connector/ejbca/rest/EjbcaRestApiClient.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/AttributeService.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/DiscoveryAttributeService.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/EjbcaService.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/AuthorityInstanceServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/CertificateEjbcaServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryAttributeServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/EjbcaServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/service/impl/EndEntityEjbcaServiceImpl.java
  src/main/java/com/czertainly/ca/connector/ejbca/util/CertificateUtil.java
  src/main/java/com/czertainly/ca/connector/ejbca/util/LocalAttributeUtil.java
  src/main/java/com/czertainly/ca/connector/ejbca/util/MetaDefinitions.java
  src/main/java/db/migration/V202211031300__AttributeV2Changes.java
  src/main/java/db/migration/V202211112000__MetadataToInfoAttributeMigration.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/czertainly/ca/connector/ejbca/DatabaseMigrationTest.java
  src/test/java/com/czertainly/ca/connector/ejbca/EJBCAIT.java
  src/test/java/com/czertainly/ca/connector/ejbca/config/TrustedCertificatesConfigTest.java
Labels: ignore-for-release
